### ISSUE TITLE
MIT vs private License

### ISSUE THREAD

**Issue by chorner** [fabscale/ember-cognito-identity#671]
https://github.com/fabscale/ember-cognito-identity#license
https://github.com/fabscale/ember-cognito-identity/packages/16374#installation

The above state MIT but provide instructions to install a private version (installing latest rather than 1.0.0).  The license file now says private:  https://github.com/fabscale/ember-cognito-identity/blob/main/LICENSE.md

The remaining references to MIT should be removed or restored back to MIT.

I'm obviously disappointed to see you repeal your license, but if that's your choice let me know so I can start from scratch (rather than contribute to yours).

**Comment by mydea** [comment]
Huh, interesting. That is not really on purpose, but we started out implementing this internally and made it public at a later point. I guess I forgot to actually update the licence file! I will update it to reflect MIT.

**Comment by mydea** [comment]
Released as 3.6.0!

**Comment by chorner** [comment]
👍
