### ISSUE TITLE
Allow "USER_PASSWORD_AUTH" via config/environment.js

### ISSUE THREAD

**Issue by hoIIer** [fabscale/ember-cognito-identity#722]
This library seems to enforce `USER_SRP_AUTH` where I want to use `USER_PASSWORD_AUTH`.

Can we add a config to enable configuring the authentication flow type similar to how [ember-cognito](https://github.com/adopted-ember-addons/ember-cognito#optional-configuration) does?

**Comment by hoIIer** [comment]
The following line should be added [here](https://github.com/fabscale/ember-cognito-identity/blob/main/addon/utils/cognito/authenticate-user.ts#L31):
```
  cognitoUser.setAuthenticationFlowType(<config.cognito.authenticationFlowType>);

```

**Comment by mydea** [comment]
That should be doable!

**Comment by mydea** [comment]
Could you check if this works as expected - I don't really have a setup to test this properly:
https://github.com/fabscale/ember-cognito-identity/tree/fn/authentication-flow

**Comment by hoIIer** [comment]
sorry slammed today and didn't get to testing it, but that looks like it should work
