### ISSUE TITLE
Add "identityToken" to cognitoData and rename "jwtToken" to "accessToken"

### ISSUE THREAD

**Issue by hoIIer** [fabscale/ember-cognito-identity#723]
The cognitoData object contains a property `jwtToken` which stores the returned Access Token from Cognito.

In another issue I'm proposing allowing alternative authentication flow types e.g. USER_PASSWORD_AUTH, where that flow type requires the Cognito Identity Token instead of the Access Token (both are returned in the authentication http request).

I'm proposing we add `identityToken` and `accessToken` to `cognitoData` and remove `jwtToken`.

**Comment by hoIIer** [comment]
**note I see that the idToken is available via `cognito.cognitoData.cognitoUserSession.idToken.jwtToken`, maybe we can still add it to the core object for convenience?

**Comment by mydea** [comment]
Hmm, I guess that would make sense. We can add accessToken & identityToken and leave jwtToken for now, so it is backwards compatible!

**Comment by mydea** [comment]
I have added `getAccessToken()` and `getIdToken()` shortcuts to the `cognitoData` object. Note that those will return the _full cognito objects_, not the jwt token. This is also the main reason why I named it `jwtToken` and not `accessToken` originally, as it can be confusing why this is not returning an CognitoAccessToken but a string. IMHO this is still easier than accessing it through the rather verbose `cognitoUserSession`, you'll have to do `cognito.cognitoData.getIdToken().jwtToken` to get the jwtToken of the idToken (but you can also access e.g. the expiration date etc. of the idToken easily there)

**Comment by hoIIer** [comment]
awesome! thanks @mydea
