### ISSUE TITLE
InvalidAuthorizationError should not be overwritten.

### ISSUE THREAD

**Issue by hoIIer** [fabscale/ember-cognito-identity#783]
https://github.com/fabscale/ember-cognito-identity/blob/b0c51f9363fb40dc3ee2fef98547aa98de32100d/addon/errors/cognito.ts#L75

Curious if there's a reason we overwrite this instead of returning the native cognito/best practice response of "Incorrect username or password."?

**Comment by mydea** [comment]
IMHO it is not best practice, the user experience is much better to show if the user or the password is incorrect - the security gains by obscuring this are miniscule, you can figure that out from the network tab (or by trying password reset, or signing up) anyhow. 

If you feel you want to show a more generic error, you can of course always catch this exception and provide a different message anyhow :)

**Comment by hoIIer** [comment]
@mydea I won't bike shed and did just catch it, although I feel like it should be in reverse where the native response is returned and the current response is caught/returned.

Cheers
